### ISSUE TITLE
Cannot invoke "org.bukkit.inventory.meta.ItemMeta.hasItemName()" because "itemMeta" is null

### ISSUE THREAD

**Issue by smscentras** [Rosewood-Development/RoseStacker#141]
[Craft Scheduler Thread - 83 - RoseStacker/WARN]: [RoseStacker] Plugin RoseStacker v1.5.31 generated an exception while executing task 78
java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.meta.ItemMeta.hasItemName()" because "itemMeta" is null
	at RoseStacker-1.5.31.jar/dev.rosewood.rosestacker.stack.StackedItem.updateDisplay(StackedItem.java:103) ~[RoseStacker-1.5.31.jar:?]
	at RoseStacker-1.5.31.jar/dev.rosewood.rosestacker.stack.StackingThread.tryStackItem(StackingThread.java:1087) ~[RoseStacker-1.5.31.jar:?]
	at RoseStacker-1.5.31.jar/dev.rosewood.rosestacker.stack.StackingThread.stackItems(StackingThread.java:220) ~[RoseStacker-1.5.31.jar:?]
	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.21.1.jar:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by smscentras** [comment]
[Craft Scheduler Thread - 316 - RoseStacker/WARN]: [RoseStacker] Plugin RoseStacker v1.5.31 generated an exception while executing task 78
java.lang.NullPointerException: null

**Comment by Esophose** [comment]
Should be fixed in 51f04b2fb108ca28e2be48960d489768f323d406
https://jenkins.rosewooddev.io/job/Rosewood%20Development/job/RoseStacker/270/artifact/build/libs/RoseStacker-1.5.32-SNAPSHOT.jar

**Comment by smscentras** [comment]
> Should be fixed in [51f04b2](https://github.com/Rosewood-Development/RoseStacker/commit/51f04b2fb108ca28e2be48960d489768f323d406) https://jenkins.rosewooddev.io/job/Rosewood%20Development/job/RoseStacker/270/artifact/build/libs/RoseStacker-1.5.32-SNAPSHOT.jar

not fixed:
`[Craft Scheduler Thread - 2825 - RoseStacker/WARN]: [RoseStacker] Plugin RoseStacker v1.5.32-SNAPSHOT generated an exception while executing task 78
java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.meta.ItemMeta.hasItemName()" because "itemMeta" is null
	at RoseStacker-1.5.32-SNAPSHOT.jar/dev.rosewood.rosestacker.stack.StackedItem.updateDisplay(StackedItem.java:104) ~[RoseStacker-1.5.32-SNAPSHOT.jar:?]
	at RoseStacker-1.5.32-SNAPSHOT.jar/dev.rosewood.rosestacker.stack.StackingThread.tryStackItem(StackingThread.java:1088) ~[RoseStacker-1.5.32-SNAPSHOT.jar:?]
	at RoseStacker-1.5.32-SNAPSHOT.jar/dev.rosewood.rosestacker.stack.StackingThread.stackItems(StackingThread.java:220) ~[RoseStacker-1.5.32-SNAPSHOT.jar:?]
	at RoseStacker-1.5.32-SNAPSHOT.jar/dev.rosewood.rosestacker.lib.rosegarden.scheduler.RoseScheduler.lambda$wrap$0(RoseScheduler.java:158) ~[RoseStacker-1.5.32-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.21.1.jar:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]`
